// Code generated by AgenticGoKit scaffold; DO NOT EDIT.
// This file activates selected providers via blank imports.
package main

import (
    // Orchestrator factory (mode-specific)
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/sequential"

    // Ensure base orchestrator registration
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/default"

    // Runner (default)
    _ "github.com/kunalkushwaha/agenticgokit/plugins/runner/default"

    // Logging provider (zerolog)
    _ "github.com/kunalkushwaha/agenticgokit/plugins/logging/zerolog"
    // Agents (configurable factory registration)
    _ "github.com/kunalkushwaha/agenticgokit/plugins/agents/configurable"
    _ "github.com/kunalkushwaha/agenticgokit/plugins/llm/openai"
)
