package templates

const PluginsBundleTemplate = `// Code generated by AgenticGoKit scaffold; DO NOT EDIT.
// This file activates selected providers via blank imports.
package main

import (
    // Orchestrator factory (mode-specific)
    {{- if eq .Config.OrchestrationMode "collaborative" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/collaborative"
    {{- else if eq .Config.OrchestrationMode "sequential" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/sequential"
    {{- else if eq .Config.OrchestrationMode "loop" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/loop"
    {{- else if eq .Config.OrchestrationMode "mixed" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/mixed"
    {{- else }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/route"
    {{- end }}

    // Ensure base orchestrator registration
    _ "github.com/kunalkushwaha/agenticgokit/plugins/orchestrator/default"

    // Runner (default)
    _ "github.com/kunalkushwaha/agenticgokit/plugins/runner/default"

    // Logging provider (zerolog)
    _ "github.com/kunalkushwaha/agenticgokit/plugins/logging/zerolog"

    {{- /* LLM provider based on config */}}
    {{- if eq .Config.Provider "openai" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/llm/openai"
    {{- else if eq .Config.Provider "azure" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/llm/azureopenai"
    {{- else if eq .Config.Provider "ollama" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/llm/ollama"
    {{- end }}

    {{- /* Memory provider based on config */}}
    {{- if .Config.MemoryEnabled }}
        {{- if eq .Config.MemoryProvider "pgvector" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/memory/pgvector"
        {{- else if eq .Config.MemoryProvider "weaviate" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/memory/weaviate"
        {{- else if eq .Config.MemoryProvider "memory" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/memory/memory"
        {{- end }}
    {{- end }}

    {{- /* MCP transport/registry/cache based on config */}}
    {{- if .Config.MCPEnabled }}
    // MCP: transport, registry, and optional cache backend
    _ "github.com/kunalkushwaha/agenticgokit/plugins/mcp/registry/memory"
    {{- if or (eq .Config.MCPTransport "") (eq .Config.MCPTransport "tcp") }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/mcp/tcp"
    {{- else if eq .Config.MCPTransport "stdio" }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/mcp/stdio"
    {{- else }}
    // Unknown transport - include default manager only
    _ "github.com/kunalkushwaha/agenticgokit/plugins/mcp/default"
    {{- end }}
    {{- if .Config.WithCache }}
        {{- if or (eq .Config.CacheBackend "") (eq .Config.CacheBackend "memory") }}
    _ "github.com/kunalkushwaha/agenticgokit/plugins/mcp/cache/memory"
        {{- end }}
    {{- end }}
    {{- end }}
)
`
